let cat = [
  {
    id: 1,
    DefaultIMG: "0XYvRd7oD",
    catName: "Abyssinian",
    catExplanation: "Balinese are curious",
    tag: "tabby",
    tagList: "Affectionate",
  },
  {
    id: 2,
    DefaultIMG: "ozEvzdVM",
    catName: "Aegean",
    catExplanation: "den eyes and",
    tag: "silver",
    tagList: "AustraliaAustralia",
  },
  {
    id: 3,
    DefaultIMG: "k71ULYfRr",
    catName: "Abyssinian",
    catExplanation: "Ctenophorus ornatus",
    tag: "white",
    tagList: "Alert",
  },
  {
    id: 4,
    DefaultIMG: "B1ERTmgph",
    catName: "Abyssinianaaa",
    catExplanation: "Leprocaulinus vipera",
    tag: "caos",
    tagList: "Easy Going",
  },
];

let data = [
  {
    id: 1,
    DefaultIMG: "http://dummyimage.com/225x100.png/5fa2dd/ffffff",
    catName: "Legaan, water",
    catExplanation: "Varanus salvator",
    tag: "fturfs0",
    tagList: "Turfs",
  },
  {
    id: 2,
    DefaultIMG: "http://dummyimage.com/237x100.png/dddddd/000000",
    catName: "Desert kangaroo rat",
    catExplanation: "Dipodomys deserti",
    tag: "lronci1",
    tagList: "Turfs",
  },
  {
    id: 3,
    DefaultIMG: "http://dummyimage.com/190x100.png/dddddd/000000",
    catName: "Dragon, ornate rock",
    catExplanation: "Ctenophorus ornatus",
    tag: "gdaulton2",
    tagList: "Daulton",
  },
  {
    id: 4,
    DefaultIMG: "http://dummyimage.com/144x100.png/cc0000/ffffff",
    catName: "Black-backed jackal",
    catExplanation: "Canis mesomelas",
    tag: "ethulborn3",
    tagList: "Thulborn",
  },
  {
    id: 5,
    DefaultIMG: "http://dummyimage.com/165x100.png/dddddd/000000",
    catName: "Rufous tree pie",
    catExplanation: "Dendrocitta vagabunda",
    tag: "ssacaze4",
    tagList: "Sacaze",
  },
  {
    id: 6,
    DefaultIMG: "http://dummyimage.com/139x100.png/cc0000/ffffff",
    catName: "Stick insect",
    catExplanation: "Leprocaulinus vipera",
    tag: "nbrinkworth5",
    tagList: "Brinkworth",
  },
  {
    id: 7,
    DefaultIMG: "http://dummyimage.com/166x100.png/5fa2dd/ffffff",
    catName: "Porcupine, north american",
    catExplanation: "Erethizon dorsatum",
    tag: "cmartinot6",
    tagList: "Martinot",
  },
  {
    id: 8,
    DefaultIMG: "http://dummyimage.com/102x100.png/5fa2dd/ffffff",
    catName: "Porcupine, north american",
    catExplanation: "Erethizon dorsatum",
    tag: "mbutland7",
    tagList: "Butland",
  },
  {
    id: 9,
    DefaultIMG: "http://dummyimage.com/177x100.png/dddddd/000000",
    catName: "Trumpeter, green-winged",
    catExplanation: "Psophia viridis",
    tag: "ldalziell8",
    tagList: "Dalziell",
  },
  {
    id: 10,
    DefaultIMG: "http://dummyimage.com/225x100.png/dddddd/000000",
    catName: "Cormorant, large",
    catExplanation: "Phalacrocorax carbo",
    tag: "eimms9",
    tagList: "Imms",
  },
  {
    id: 11,
    DefaultIMG: "http://dummyimage.com/209x100.png/cc0000/ffffff",
    catName: "Deer, swamp",
    catExplanation: "Cervus duvauceli",
    tag: "fdrexela",
    tagList: "Drexel",
  },
  {
    id: 12,
    DefaultIMG: "http://dummyimage.com/159x100.png/dddddd/000000",
    catName: "Black-collared barbet",
    catExplanation: "Lybius torquatus",
    tag: "mdunsb",
    tagList: "Duns",
  },
  {
    id: 13,
    DefaultIMG: "http://dummyimage.com/176x100.png/5fa2dd/ffffff",
    catName: "Paddy heron (unidentified)",
    catExplanation: "unavailable",
    tag: "lduddlec",
    tagList: "Duddle",
  },
  {
    id: 14,
    DefaultIMG: "http://dummyimage.com/224x100.png/ff4444/ffffff",
    catName: "Ibex",
    catExplanation: "Capra ibex",
    tag: "koaked",
    tagList: "Oake",
  },
  {
    id: 15,
    DefaultIMG: "http://dummyimage.com/239x100.png/cc0000/ffffff",
    catName: "Cockatoo, roseate",
    catExplanation: "Eolophus roseicapillus",
    tag: "erayhille",
    tagList: "Rayhill",
  },
  {
    id: 16,
    DefaultIMG: "http://dummyimage.com/110x100.png/cc0000/ffffff",
    catName: "Openbill, asian",
    catExplanation: "Anastomus oscitans",
    tag: "mwhitleyf",
    tagList: "Whitley",
  },
  {
    id: 17,
    DefaultIMG: "http://dummyimage.com/192x100.png/5fa2dd/ffffff",
    catName: "Bunting, crested",
    catExplanation: "Melophus lathami",
    tag: "kpendreighg",
    tagList: "Pendreigh",
  },
  {
    id: 18,
    DefaultIMG: "http://dummyimage.com/109x100.png/5fa2dd/ffffff",
    catName: "Snake, tiger",
    catExplanation: "Notechis semmiannulatus",
    tag: "scrinageh",
    tagList: "Crinage",
  },
  {
    id: 19,
    DefaultIMG: "http://dummyimage.com/144x100.png/cc0000/ffffff",
    catName: "Burrowing owl",
    catExplanation: "Speotyte cuniculata",
    tag: "ksingersi",
    tagList: "Singers",
  },
  {
    id: 20,
    DefaultIMG: "http://dummyimage.com/174x100.png/5fa2dd/ffffff",
    catName: "Yellow-bellied marmot",
    catExplanation: "Marmota flaviventris",
    tag: "jgowerj",
    tagList: "Gower",
  },
  {
    id: 21,
    DefaultIMG: "http://dummyimage.com/207x100.png/5fa2dd/ffffff",
    catName: "Rat, desert kangaroo",
    catExplanation: "Dipodomys deserti",
    tag: "ehoffmank",
    tagList: "Hoffman",
  },
  {
    id: 22,
    DefaultIMG: "http://dummyimage.com/217x100.png/ff4444/ffffff",
    catName: "Jaeger, long-tailed",
    catExplanation: "Stercorarius longicausus",
    tag: "dkegginl",
    tagList: "Keggin",
  },
  {
    id: 23,
    DefaultIMG: "http://dummyimage.com/230x100.png/dddddd/000000",
    catName: "Oryx, fringe-eared",
    catExplanation: "Oryx gazella callotis",
    tag: "jwhenmanm",
    tagList: "Whenman",
  },
  {
    id: 24,
    DefaultIMG: "http://dummyimage.com/108x100.png/cc0000/ffffff",
    catName: "Capuchin, weeper",
    catExplanation: "Cebus nigrivittatus",
    tag: "fhansien",
    tagList: "Hansie",
  },
  {
    id: 25,
    DefaultIMG: "http://dummyimage.com/120x100.png/ff4444/ffffff",
    catName: "Catfish, blue",
    catExplanation: "Ictalurus furcatus",
    tag: "mdyneleyo",
    tagList: "Dyneley",
  },
  {
    id: 26,
    DefaultIMG: "http://dummyimage.com/127x100.png/cc0000/ffffff",
    catName: "Turkey vulture",
    catExplanation: "Cathartes aura",
    tag: "ttriponyp",
    tagList: "Tripony",
  },
  {
    id: 27,
    DefaultIMG: "http://dummyimage.com/200x100.png/ff4444/ffffff",
    catName: "Nuthatch, red-breasted",
    catExplanation: "Sitta canadensis",
    tag: "cmoralq",
    tagList: "Moral",
  },
  {
    id: 28,
    DefaultIMG: "http://dummyimage.com/158x100.png/cc0000/ffffff",
    catName: "Comb duck",
    catExplanation: "Sarkidornis melanotos",
    tag: "cstirtler",
    tagList: "Stirtle",
  },
  {
    id: 29,
    DefaultIMG: "http://dummyimage.com/222x100.png/cc0000/ffffff",
    catName: "Egyptian goose",
    catExplanation: "Alopochen aegyptiacus",
    tag: "mhardakers",
    tagList: "Hardaker",
  },
  {
    id: 30,
    DefaultIMG: "http://dummyimage.com/232x100.png/5fa2dd/ffffff",
    catName: "Zebra, plains",
    catExplanation: "Equus burchelli",
    tag: "phastyt",
    tagList: "Hasty",
  },
  {
    id: 31,
    DefaultIMG: "http://dummyimage.com/157x100.png/dddddd/000000",
    catName: "Gull, lava",
    catExplanation: "Larus fuliginosus",
    tag: "ubrimbleu",
    tagList: "Brimble",
  },
  {
    id: 32,
    DefaultIMG: "http://dummyimage.com/217x100.png/dddddd/000000",
    catName: "Stork, white",
    catExplanation: "Ciconia ciconia",
    tag: "kludyv",
    tagList: "Ludy",
  },
  {
    id: 33,
    DefaultIMG: "http://dummyimage.com/128x100.png/dddddd/000000",
    catName: "Cat, long-tailed spotted",
    catExplanation: "Felis wiedi or Leopardus weidi",
    tag: "dswyersexeyw",
    tagList: "Swyer-Sexey",
  },
  {
    id: 34,
    DefaultIMG: "http://dummyimage.com/149x100.png/dddddd/000000",
    catName: "Warthog",
    catExplanation: "Phacochoerus aethiopus",
    tag: "gbaughnx",
    tagList: "Baughn",
  },
  {
    id: 35,
    DefaultIMG: "http://dummyimage.com/115x100.png/dddddd/000000",
    catName: "Gull, swallow-tail",
    catExplanation: "Creagrus furcatus",
    tag: "oschwandy",
    tagList: "Schwand",
  },
  {
    id: 36,
    DefaultIMG: "http://dummyimage.com/170x100.png/dddddd/000000",
    catName: "Lizard, giant girdled",
    catExplanation: "Cordylus giganteus",
    tag: "bmcleodz",
    tagList: "McLeod",
  },
  {
    id: 37,
    DefaultIMG: "http://dummyimage.com/151x100.png/cc0000/ffffff",
    catName: "Indian tree pie",
    catExplanation: "Dendrocitta vagabunda",
    tag: "ssandwich10",
    tagList: "Sandwich",
  },
  {
    id: 38,
    DefaultIMG: "http://dummyimage.com/143x100.png/dddddd/000000",
    catName: "Huron",
    catExplanation: "Galictis vittata",
    tag: "playcock11",
    tagList: "Laycock",
  },
  {
    id: 39,
    DefaultIMG: "http://dummyimage.com/165x100.png/cc0000/ffffff",
    catName: "Galapagos dove",
    catExplanation: "Zenaida galapagoensis",
    tag: "cpett12",
    tagList: "Pett",
  },
  {
    id: 40,
    DefaultIMG: "http://dummyimage.com/106x100.png/5fa2dd/ffffff",
    catName: "Blue and gold macaw",
    catExplanation: "Ara ararauna",
    tag: "nwarwicker13",
    tagList: "Warwicker",
  },
  {
    id: 41,
    DefaultIMG: "http://dummyimage.com/133x100.png/ff4444/ffffff",
    catName: "Porcupine, prehensile-tailed",
    catExplanation: "Coendou prehensilis",
    tag: "yomulderrig14",
    tagList: "O' Mulderrig",
  },
  {
    id: 42,
    DefaultIMG: "http://dummyimage.com/102x100.png/ff4444/ffffff",
    catName: "Rattlesnake, dusky",
    catExplanation: "Crotalus triseriatus",
    tag: "bnovello15",
    tagList: "Novello",
  },
  {
    id: 43,
    DefaultIMG: "http://dummyimage.com/145x100.png/ff4444/ffffff",
    catName: "Chipmunk, least",
    catExplanation: "Eutamias minimus",
    tag: "nmatias16",
    tagList: "Matias",
  },
  {
    id: 44,
    DefaultIMG: "http://dummyimage.com/138x100.png/ff4444/ffffff",
    catName: "Bengal vulture",
    catExplanation: "Gyps bengalensis",
    tag: "mlarking17",
    tagList: "Larking",
  },
  {
    id: 45,
    DefaultIMG: "http://dummyimage.com/134x100.png/cc0000/ffffff",
    catName: "Oriental white-backed vulture",
    catExplanation: "Gyps bengalensis",
    tag: "nbrafield18",
    tagList: "Brafield",
  },
  {
    id: 46,
    DefaultIMG: "http://dummyimage.com/101x100.png/5fa2dd/ffffff",
    catName: "Crowned hawk-eagle",
    catExplanation: "Spizaetus coronatus",
    tag: "sbeccles19",
    tagList: "Beccles",
  },
  {
    id: 47,
    DefaultIMG: "http://dummyimage.com/218x100.png/5fa2dd/ffffff",
    catName: "Python, carpet",
    catExplanation: "Morelia spilotes variegata",
    tag: "emcdermot1a",
    tagList: "McDermot",
  },
  {
    id: 48,
    DefaultIMG: "http://dummyimage.com/215x100.png/cc0000/ffffff",
    catName: "Red-breasted cockatoo",
    catExplanation: "Eolophus roseicapillus",
    tag: "ilequeux1b",
    tagList: "Lequeux",
  },
  {
    id: 49,
    DefaultIMG: "http://dummyimage.com/133x100.png/ff4444/ffffff",
    catName: "Gambel's quail",
    catExplanation: "Callipepla gambelii",
    tag: "wfrankcombe1c",
    tagList: "Frankcombe",
  },
  {
    id: 50,
    DefaultIMG: "http://dummyimage.com/131x100.png/5fa2dd/ffffff",
    catName: "Parakeet, rose-ringed",
    catExplanation: "Psittacula krameri",
    tag: "wpark1d",
    tagList: "Park",
  },
  {
    id: 51,
    DefaultIMG: "http://dummyimage.com/112x100.png/ff4444/ffffff",
    catName: "Common nighthawk",
    catExplanation: "Chordeiles minor",
    tag: "sveschi1e",
    tagList: "Veschi",
  },
  {
    id: 52,
    DefaultIMG: "http://dummyimage.com/189x100.png/5fa2dd/ffffff",
    catName: "Parrot, hawk-headed",
    catExplanation: "Deroptyus accipitrinus",
    tag: "mberrill1f",
    tagList: "Berrill",
  },
  {
    id: 53,
    DefaultIMG: "http://dummyimage.com/219x100.png/ff4444/ffffff",
    catName: "African porcupine",
    catExplanation: "Hystrix cristata",
    tag: "aibanez1g",
    tagList: "Ibanez",
  },
  {
    id: 54,
    DefaultIMG: "http://dummyimage.com/185x100.png/5fa2dd/ffffff",
    catName: "Frogmouth, tawny",
    catExplanation: "Podargus strigoides",
    tag: "plorait1h",
    tagList: "Lorait",
  },
  {
    id: 55,
    DefaultIMG: "http://dummyimage.com/202x100.png/cc0000/ffffff",
    catName: "Springbok",
    catExplanation: "Antidorcas marsupialis",
    tag: "mhazzard1i",
    tagList: "Hazzard",
  },
  {
    id: 56,
    DefaultIMG: "http://dummyimage.com/121x100.png/ff4444/ffffff",
    catName: "Owl, madagascar hawk",
    catExplanation: "Ninox superciliaris",
    tag: "afaughny1j",
    tagList: "Faughny",
  },
  {
    id: 57,
    DefaultIMG: "http://dummyimage.com/224x100.png/ff4444/ffffff",
    catName: "Rhesus monkey",
    catExplanation: "Macaca mulatta",
    tag: "hpotes1k",
    tagList: "Potes",
  },
  {
    id: 58,
    DefaultIMG: "http://dummyimage.com/107x100.png/ff4444/ffffff",
    catName: "Barking gecko",
    catExplanation: "Phylurus milli",
    tag: "vdolle1l",
    tagList: "Dolle",
  },
  {
    id: 59,
    DefaultIMG: "http://dummyimage.com/101x100.png/5fa2dd/ffffff",
    catName: "Cat, ringtail",
    catExplanation: "Bassariscus astutus",
    tag: "mreignould1m",
    tagList: "Reignould",
  },
  {
    id: 60,
    DefaultIMG: "http://dummyimage.com/220x100.png/ff4444/ffffff",
    catName: "Roller, lilac-breasted",
    catExplanation: "Coracias caudata",
    tag: "adando1n",
    tagList: "Dando",
  },
  {
    id: 61,
    DefaultIMG: "http://dummyimage.com/171x100.png/ff4444/ffffff",
    catName: "Tern, royal",
    catExplanation: "Thalasseus maximus",
    tag: "espurdon1o",
    tagList: "Spurdon",
  },
  {
    id: 62,
    DefaultIMG: "http://dummyimage.com/164x100.png/dddddd/000000",
    catName: "Armadillo, nine-banded",
    catExplanation: "Dasypus novemcinctus",
    tag: "dkernan1p",
    tagList: "Kernan",
  },
  {
    id: 63,
    DefaultIMG: "http://dummyimage.com/116x100.png/cc0000/ffffff",
    catName: "Grey-footed squirrel",
    catExplanation: "Paraxerus cepapi",
    tag: "dorviss1q",
    tagList: "Orviss",
  },
  {
    id: 64,
    DefaultIMG: "http://dummyimage.com/210x100.png/ff4444/ffffff",
    catName: "Buffalo, american",
    catExplanation: "Bison bison",
    tag: "wkeays1r",
    tagList: "Keays",
  },
  {
    id: 65,
    DefaultIMG: "http://dummyimage.com/175x100.png/cc0000/ffffff",
    catName: "Gull, lava",
    catExplanation: "Larus fuliginosus",
    tag: "sfaustin1s",
    tagList: "Faustin",
  },
  {
    id: 66,
    DefaultIMG: "http://dummyimage.com/234x100.png/cc0000/ffffff",
    catName: "Hudsonian godwit",
    catExplanation: "Limosa haemastica",
    tag: "haukland1t",
    tagList: "Aukland",
  },
  {
    id: 67,
    DefaultIMG: "http://dummyimage.com/193x100.png/cc0000/ffffff",
    catName: "Rat, arboral spiny",
    catExplanation: "Echimys chrysurus",
    tag: "apeatheyjohns1u",
    tagList: "Peatheyjohns",
  },
  {
    id: 68,
    DefaultIMG: "http://dummyimage.com/206x100.png/5fa2dd/ffffff",
    catName: "Purple grenadier",
    catExplanation: "Uraeginthus granatina",
    tag: "tkapelhof1v",
    tagList: "Kapelhof",
  },
  {
    id: 69,
    DefaultIMG: "http://dummyimage.com/129x100.png/ff4444/ffffff",
    catName: "Greater rhea",
    catExplanation: "Rhea americana",
    tag: "kwaber1w",
    tagList: "Waber",
  },
  {
    id: 70,
    DefaultIMG: "http://dummyimage.com/153x100.png/5fa2dd/ffffff",
    catName: "Little brown bat",
    catExplanation: "Myotis lucifugus",
    tag: "ncosyns1x",
    tagList: "Cosyns",
  },
  {
    id: 71,
    DefaultIMG: "http://dummyimage.com/114x100.png/cc0000/ffffff",
    catName: "Giant otter",
    catExplanation: "Pteronura brasiliensis",
    tag: "asutch1y",
    tagList: "Sutch",
  },
  {
    id: 72,
    DefaultIMG: "http://dummyimage.com/111x100.png/cc0000/ffffff",
    catName: "Stork, marabou",
    catExplanation: "Leptoptilos crumeniferus",
    tag: "ctetlow1z",
    tagList: "Tetlow",
  },
  {
    id: 73,
    DefaultIMG: "http://dummyimage.com/163x100.png/dddddd/000000",
    catName: "Raven, cape",
    catExplanation: "Corvus albicollis",
    tag: "sdennert20",
    tagList: "Dennert",
  },
  {
    id: 74,
    DefaultIMG: "http://dummyimage.com/111x100.png/cc0000/ffffff",
    catName: "Mississippi alligator",
    catExplanation: "Alligator mississippiensis",
    tag: "mmazzey21",
    tagList: "Mazzey",
  },
  {
    id: 75,
    DefaultIMG: "http://dummyimage.com/218x100.png/5fa2dd/ffffff",
    catName: "Steller's sea lion",
    catExplanation: "Eumetopias jubatus",
    tag: "mmafham22",
    tagList: "Mafham",
  },
  {
    id: 76,
    DefaultIMG: "http://dummyimage.com/147x100.png/cc0000/ffffff",
    catName: "Tawny frogmouth",
    catExplanation: "Podargus strigoides",
    tag: "tklimkin23",
    tagList: "Klimkin",
  },
  {
    id: 77,
    DefaultIMG: "http://dummyimage.com/105x100.png/cc0000/ffffff",
    catName: "Cat, cape wild",
    catExplanation: "Felis libyca",
    tag: "dbexley24",
    tagList: "Bexley",
  },
  {
    id: 78,
    DefaultIMG: "http://dummyimage.com/219x100.png/ff4444/ffffff",
    catName: "Shrike, common boubou",
    catExplanation: "Laniarius ferrugineus",
    tag: "scorking25",
    tagList: "Corking",
  },
  {
    id: 79,
    DefaultIMG: "http://dummyimage.com/136x100.png/dddddd/000000",
    catName: "Jaguar",
    catExplanation: "Panthera onca",
    tag: "tpeegrem26",
    tagList: "Peegrem",
  },
  {
    id: 80,
    DefaultIMG: "http://dummyimage.com/118x100.png/dddddd/000000",
    catName: "Grenadier, common",
    catExplanation: "Uraeginthus granatina",
    tag: "eknevet27",
    tagList: "Knevet",
  },
  {
    id: 81,
    DefaultIMG: "http://dummyimage.com/213x100.png/5fa2dd/ffffff",
    catName: "Sally lightfoot crab",
    catExplanation: "Graspus graspus",
    tag: "grichfield28",
    tagList: "Richfield",
  },
  {
    id: 82,
    DefaultIMG: "http://dummyimage.com/220x100.png/cc0000/ffffff",
    catName: "Brush-tailed phascogale",
    catExplanation: "Phascogale tapoatafa",
    tag: "ncutmere29",
    tagList: "Cutmere",
  },
  {
    id: 83,
    DefaultIMG: "http://dummyimage.com/213x100.png/cc0000/ffffff",
    catName: "Hottentot teal",
    catExplanation: "Anas punctata",
    tag: "wmaletratt2a",
    tagList: "Maletratt",
  },
  {
    id: 84,
    DefaultIMG: "http://dummyimage.com/175x100.png/cc0000/ffffff",
    catName: "Cattle egret",
    catExplanation: "Bubulcus ibis",
    tag: "rnoir2b",
    tagList: "Noir",
  },
  {
    id: 85,
    DefaultIMG: "http://dummyimage.com/144x100.png/dddddd/000000",
    catName: "Yak",
    catExplanation: "Bos mutus",
    tag: "asacco2c",
    tagList: "Sacco",
  },
  {
    id: 86,
    DefaultIMG: "http://dummyimage.com/137x100.png/dddddd/000000",
    catName: "Australian sea lion",
    catExplanation: "Neophoca cinerea",
    tag: "jhildrew2d",
    tagList: "Hildrew",
  },
  {
    id: 87,
    DefaultIMG: "http://dummyimage.com/148x100.png/5fa2dd/ffffff",
    catName: "Boubou, southern",
    catExplanation: "Laniarius ferrugineus",
    tag: "vyanshonok2e",
    tagList: "Yanshonok",
  },
  {
    id: 88,
    DefaultIMG: "http://dummyimage.com/180x100.png/dddddd/000000",
    catName: "Beaver, european",
    catExplanation: "Castor fiber",
    tag: "rseedman2f",
    tagList: "Seedman",
  },
  {
    id: 89,
    DefaultIMG: "http://dummyimage.com/171x100.png/cc0000/ffffff",
    catName: "American badger",
    catExplanation: "Taxidea taxus",
    tag: "lellson2g",
    tagList: "Ellson",
  },
  {
    id: 90,
    DefaultIMG: "http://dummyimage.com/230x100.png/ff4444/ffffff",
    catName: "Gazer, sun",
    catExplanation: "Cordylus giganteus",
    tag: "hcopley2h",
    tagList: "Copley",
  },
  {
    id: 91,
    DefaultIMG: "http://dummyimage.com/203x100.png/cc0000/ffffff",
    catName: "Sportive lemur",
    catExplanation: "Lepilemur rufescens",
    tag: "rclive2i",
    tagList: "Clive",
  },
  {
    id: 92,
    DefaultIMG: "http://dummyimage.com/120x100.png/5fa2dd/ffffff",
    catName: "Two-toed sloth",
    catExplanation: "Choloepus hoffmani",
    tag: "mniemiec2j",
    tagList: "Niemiec",
  },
  {
    id: 93,
    DefaultIMG: "http://dummyimage.com/212x100.png/ff4444/ffffff",
    catName: "Vervet monkey",
    catExplanation: "Cercopithecus aethiops",
    tag: "wbatcock2k",
    tagList: "Batcock",
  },
  {
    id: 94,
    DefaultIMG: "http://dummyimage.com/107x100.png/cc0000/ffffff",
    catName: "Cat, long-tailed spotted",
    catExplanation: "Felis wiedi or Leopardus weidi",
    tag: "besherwood2l",
    tagList: "Esherwood",
  },
  {
    id: 95,
    DefaultIMG: "http://dummyimage.com/120x100.png/cc0000/ffffff",
    catName: "Stork, woolly-necked",
    catExplanation: "Ciconia episcopus",
    tag: "gedlington2m",
    tagList: "Edlington",
  },
  {
    id: 96,
    DefaultIMG: "http://dummyimage.com/220x100.png/cc0000/ffffff",
    catName: "Common wallaroo",
    catExplanation: "Macropus robustus",
    tag: "gcabrales2n",
    tagList: "Cabrales",
  },
  {
    id: 97,
    DefaultIMG: "http://dummyimage.com/115x100.png/5fa2dd/ffffff",
    catName: "Long-necked turtle",
    catExplanation: "Chelodina longicollis",
    tag: "mquarmby2o",
    tagList: "Quarmby",
  },
  {
    id: 98,
    DefaultIMG: "http://dummyimage.com/109x100.png/ff4444/ffffff",
    catName: "Red-necked wallaby",
    catExplanation: "Macropus rufogriseus",
    tag: "gneilan2p",
    tagList: "Neilan",
  },
  {
    id: 99,
    DefaultIMG: "http://dummyimage.com/219x100.png/ff4444/ffffff",
    catName: "Magistrate black colobus",
    catExplanation: "Colobus guerza",
    tag: "jatherley2q",
    tagList: "Atherley",
  },
  {
    id: 100,
    DefaultIMG: "http://dummyimage.com/161x100.png/5fa2dd/ffffff",
    catName: "Lilac-breasted roller",
    catExplanation: "Coracias caudata",
    tag: "vmuncey2r",
    tagList: "Muncey",
  },
];

export { data, cat };
// export default [data, cat];
